# Generated by Django 3.1.5 on 2021-05-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(blank=True, default=False, verbose_name='Café da manhã')),
                ('lunch', models.BooleanField(blank=True, default=False, verbose_name='Almoço')),
                ('snack', models.BooleanField(blank=True, default=False, verbose_name='Lanche da tarde')),
                ('dinner', models.BooleanField(blank=True, default=False, verbose_name='Jantar')),
                ('shower', models.BooleanField(blank=True, default=False, verbose_name='Banho')),
                ('sleep', models.BooleanField(blank=True, default=False, verbose_name='Per noite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Serviço da casa',
                'verbose_name_plural': 'Serviços da casa',
            },
        ),
    ]
