# Generated by Django 3.1.5 on 2021-05-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_person', to='people.person', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='CompanionCheckin',
            fields=[
                ('checkin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.checkin')),
            ],
            options={
                'verbose_name': 'Check-in de acompanhante',
                'verbose_name_plural': "Check-in's de acompanhante",
                'ordering': ['-created_at'],
            },
            bases=('checkin.checkin',),
        ),
        migrations.CreateModel(
            name='OtherPeopleCheckin',
            fields=[
                ('checkin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.checkin')),
                ('reason', models.CharField(choices=[('professional', 'Profissional'), ('voluntary', 'Voluntário'), ('visitor', 'Visitantes'), ('other', 'Outros')], max_length=12, verbose_name='Tipo de check-in')),
            ],
            options={
                'verbose_name': 'Check-in de outras pessoas',
                'verbose_name_plural': "Check-in's de outras pessoas",
                'ordering': ['-created_at'],
            },
            bases=('checkin.checkin',),
        ),
        migrations.CreateModel(
            name='PatientCompanionCheckin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companion_checkin', to='people.person', verbose_name='Acompanhante')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_checkin', to='people.person', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCheckin',
            fields=[
                ('checkin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkin.checkin')),
                ('chemotherapy', models.BooleanField(default=False, verbose_name='Quimioterapia')),
                ('radiotherapy', models.BooleanField(default=False, verbose_name='Radioterapia')),
                ('surgery', models.BooleanField(default=False, verbose_name='Cirurgia')),
                ('exams', models.BooleanField(default=False, verbose_name='Exames')),
                ('appointment', models.BooleanField(default=False, verbose_name='Consultas')),
                ('other', models.BooleanField(default=False, verbose_name='Outros')),
                ('ca_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número C.A.')),
                ('social_vacancy', models.BooleanField(blank=True, null=True, verbose_name='Vaga Social?')),
                ('companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companion', to='people.person', verbose_name='Acompanhante')),
            ],
            options={
                'verbose_name': 'Check-in de paciente',
                'verbose_name_plural': "Check-in's de paciente",
                'ordering': ['-created_at'],
            },
            bases=('checkin.checkin',),
        ),
    ]
