# Generated by Django 3.1.5 on 2021-05-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='people.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='patientcheckin',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companion', to='people.person', verbose_name='Acompanhante'),
        ),
    ]
