# Generated by Django 3.1.5 on 2021-05-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('checkin', '0003_companioncheckin_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcheckin',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companion', to='people.person', verbose_name='Acompanhante'),
        ),
    ]
