# Generated by Django 3.1.5 on 2021-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20210517_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpeoplecheckin',
            name='reason',
            field=models.CharField(choices=[('professional', 'Profissional'), ('voluntary', 'Voluntário'), ('visitor', 'Visitante'), ('other', 'Outro')], max_length=12, verbose_name='Tipo de check-in'),
        ),
    ]
