# Generated by Django 3.1.5 on 2021-05-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('checkin', '0005_auto_20210517_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeCompanion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkin', to='checkin.patientcheckin', verbose_name='Checkin de paciente')),
                ('new_companion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_companion', to='people.person', verbose_name='Novo acompanhante')),
            ],
        ),
    ]
