# Generated by Django 3.1.5 on 2021-05-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_changecompanion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientCompanionCheckin',
        ),
    ]
